---
- hosts: all
  tasks:
  - name: Perform an ansible "ping"
    ansible.builtin.ping:
  - name: apt install packages
    become: true
    ansible.builtin.apt:
      name:
      - build-essential
      - gcc-msp430
      - binutils-msp430
      - gdb-msp430
      - msp430mcu
      - mspdebug